### ISSUE TITLE
OpenCPN 5.2.4 & Pypilot 2.1.1 beta (openplotter)

### ISSUE THREAD

**Issue by Jamos1988** [pypilot/pypilot_pi#18]
Just updated to OpenCPN 5.2.4, then noticed that the Pypilot plugin was gone, so installed the 0.22 version from within OpenCPN, this will not sync with Pypilot. So, uninstalled the previous OpenCPN plugin with openplotter/opencpn settings manager, and installed the 0.5 version. This will not install within OpenCPN, will not become visible.

So, then I tried installing Pypilot OpenCPN plugin from GIT and this installed fine, but still cannot communicate / sync to pypilot.
How can I get Pypilot plugin to work again, without having to downgrade OpenCPN?

**Comment by seandepagnier** [comment]
the new plugin requires the new pypilot.   So assuming you are using
the old pypilot software you would need to use pypilot plugin 0.9
which is not available to install directly from within opencpn.

The other alternative is to upgrade pypilot via git, or with the
latest tinypilot image.

Sean

**Comment by Jamos1988** [comment]
So, when upgrading pypilot through openplotter, with the openplotter Tool
you don't get the newest one yet?

**Comment by Jamos1988** [comment]
Ok so I tried installing Pypilot newest version via GIT but having trouble. Cannot start the services. I am stuck at step:

"You may want to run pypilot as a service, see the scripts/debian directory"

So after I did this two things are going wrong:

- dhcpcd is not running anymore
- a lot of files that have to do with my network have been overwritten, not sure why but lost some functionality
- the services added in /etc/systemd/system are not starting:

`pi@openplotter:~ $ sudo systemctl status pypilot
● pypilot.service - pypilot
   Loaded: loaded (/etc/systemd/system/pypilot.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-11-13 13
  Process: 17571 ExecStart=/usr/local/bin/pypilot (code=exited, status=1/FAILURE
 Main PID: 17571 (code=exited, status=1/FAILURE)
`
What to do?

**Comment by rgleason** [comment]
This is very old. Please close  Jamos1988 or Sean
