### ISSUE TITLE
Plugin client shows subset of parameters after reconnect; gains vanished

### ISSUE THREAD

**Issue by marcobergman** [pypilot/pypilot_pi#25]
The pypilot_client that sits inside the plugin shows a subset of the parameters after the connection to pypilot has been interrupted. This also applies to the gains - these are gone entirely.
![Capture](https://user-images.githubusercontent.com/17980560/125929221-9a09010d-f02b-4c21-9972-96ce4079de86.PNG)

**Comment by marcobergman** [comment]
![Capture2](https://user-images.githubusercontent.com/17980560/125929402-57f1aaeb-dfd7-457a-8f2f-d95a0478590e.PNG)

**Comment by seandepagnier** [comment]
I just tried without getting this issue.   How did you get in this state?

Could you please run:
ps aux | grep python

I think maybe pypilot_boatimu is running instead?

**Comment by marcobergman** [comment]
No nothing running anymore. I can also replicate it on openplotter, latest plugin compiled from github, latest pypilot (0.25) compiled from github, running pypilot at the prompt, connecting plugin client, then hitting ^c at the prompt, checking your ps -aux|grep python, running pypilot at the prompt again, reopen gains and client screen. I have also had this problem at the boat when I wanted to change some gains, there I have opencpn running at ubuntu. 

![Capture3](https://user-images.githubusercontent.com/17980560/125966389-06a874ab-34ec-4657-b791-3ff13a1ab698.PNG)

**Comment by marcobergman** [comment]
The same thing occured on Windows with the 0.22.5.0 plugin, but NOT the 0.24.4.0 plugin. I double checked that.

**Comment by seandepagnier** [comment]
so to be clear, the newer version of the plugin does not have the problem?

I have fixed bugs over time...

**Comment by marcobergman** [comment]
Tch - I got it. The version 0.24.4.0 does not have this problem. I'll close the issue, apologies for the fuzz.

I had compiled the plugin on linux, but omitted to update to the new version in the opencpn plugin manager...

**Comment by marcobergman** [comment]
It might be a good idea to update the README file with a remark not to forget "to update to the new version in the opencpn plugin manager" as part of the build process.
