### ISSUE TITLE
Display pypilot plugin heading and command with three digits plus decimal

### ISSUE THREAD

**Issue by lurno** [pypilot/pypilot_pi#31]
For my own use I have modified src/pypilotDialog.cpp to make the output look like this, is that of interrest?
Lasse
![pypilot_mod](https://user-images.githubusercontent.com/6130578/191594276-9405d512-fa6a-43f4-897d-0a5add5f089e.jpg)

**Comment by seandepagnier** [comment]
Yes, please submit a pull request

**Comment by lurno** [comment]
Pull request submitted (to the best of my ability, its a first for me :-) )

**Comment by rgleason** [comment]
Where is this pull request?  I do not see it.
