### ISSUE TITLE
Cannot compile for Windows

### ISSUE THREAD

**Issue by rgleason** [pypilot/pypilot_pi#4]
pypilot_pi.h has
#define     MY_API_VERSION_MAJOR    1
#define     MY_API_VERSION_MINOR    10

I have api version 1.13 for Opencpn 4.2.0

These are the errors:

Build FAILED.

"C:\Users\Rick\Documents\GitHub\pypilot_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Rick\Documents\GitHub\pypilot_pi\build\pypilot_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  cl : Command line warning D9002: ignoring unknown option '-std=c++11' [C:\Users\Rick\Documents\Gi
tHub\pypilot_pi\build\pypilot_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_writer.cpp(48): warning C4005: '_CRT_S
ECURE_CPP_OVERLOAD_STANDARD_NAMES' : macro redefinition [C:\Users\Rick\Documents\GitHub\pypilot_pi\
build\pypilot_pi.vcxproj]

"C:\Users\Rick\Documents\GitHub\pypilot_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Rick\Documents\GitHub\pypilot_pi\build\pypilot_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_value.cpp(665): error C2668: 'Json::va
lueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bui
ld\pypilot_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_writer.cpp(382): error C2668: 'Json::v
alueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bu
ild\pypilot_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_writer.cpp(452): error C2668: 'Json::v
alueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bu
ild\pypilot_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_writer.cpp(670): error C2668: 'Json::v
alueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bu
ild\pypilot_pi.vcxproj]

    2 Warning(s)
    4 Error(s)

**Comment by rgleason** [comment]
Started over and recompiled. Same errors and they all look the same.:

> Build FAILED.
> "C:\Users\Rick\Documents\GitHub\pypilot_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "C:\Users\Rick\Documents\GitHub\pypilot_pi\build\pypilot_pi.vcxproj" (default target) (3) ->
> (ClCompile target) ->
>   C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_value.cpp(665): error C2668: 'Json::va
> lueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bui
> ld\pypilot_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_writer.cpp(382): error C2668: 'Json::v
> alueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bu
> ild\pypilot_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_writer.cpp(452): error C2668: 'Json::v
> alueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bu
> ild\pypilot_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\pypilot_pi\src\jsoncpp\json_writer.cpp(670): error C2668: 'Json::v
> alueToString' : ambiguous call to overloaded function [C:\Users\Rick\Documents\GitHub\pypilot_pi\bu
> ild\pypilot_pi.vcxproj]
> 
>     9 Warning(s)
>     4 Error(s)

**Comment by rgleason** [comment]
Tried opencpn.lib for v4.8.0 but we still get the errors

C++ compiler error: ambiguous call to overloaded function
https://msdn.microsoft.com/en-us/library/da60x087.aspx

**Comment by rgleason** [comment]
I think something about this code is not working
only require json to be built with c++11 
https://github.com/rgleason/pypilot_pi/commit/19133548843ad665fc3040a72ebc1c0f6190c059

Or is there a parameter to use when doing cmake to prevent json?

**Comment by rgleason** [comment]
Won't work until 5.0

**Comment by seandepagnier** [comment]
Is this fixed since we are on 5.0?

**Comment by rgleason** [comment]
Yes
