### ISSUE TITLE
Config for Servo and Tacking do not function

### ISSUE THREAD

**Issue by svkatielee** [pypilot/pypilot_pi#6]
pypilot_pi 0.9, opencpn 5.0, RPI3B+, openplotter 1.2.0

On the Config tab, all of the buttons to change the number setting in Servo and Tracking revert to the default values. ie. "Max Current 7.5 Amps", but if I click the up arrow, the value changes to 0.1, the default in the code. The same for each of the buttons.

I can't find in the code where they would be handled.

**Comment by rgleason** [comment]
@svkatielee   pLEASE close Sean has completed this. Thank you.
