### ISSUE TITLE
Also cmake and gettext needed on openplotter 2.0

### ISSUE THREAD

**Issue by marcobergman** [pypilot/pypilot_pi#9]
For compiling the plugin on a fresh openplotter image, it seems that additionally the packages cmake and gettext are needed. You might want to add this to the readme.

**Comment by cornelledepag** [comment]
Had this problem and would have saved me time if this was in the read me. 

Further addition to the readme make as sudo

**Comment by rgleason** [comment]
Marco, please close. Sean completed it.
